### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by SkorikSergey**

### CODE REVIEW

**Comment by SkorikSergey** [comment]
test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Results of automated E2E tests of Codeready on OCP: FAILURE
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-happy-path/882/)

**Pull request closed without merging**
